export const FETCH_WITHOUT_FILTERS = 'FETCH_WITHOUT_FILTERS';
export const FETCH_WITH_LANDING_SUCCESS = 'FETCH_WITH_LANDING_SUCCESS';
export const FETCH_WITH_LAUNCH_SUCCESS = 'FETCH_WITH_LAUNCH_SUCCESS';
export const FETCH_WITH_LANDING_YEAR = 'FETCH_WITH_LANDING_YEAR';
export const FETCH_WITH_ALL_RESULTS = 'FETCH_WITH_ALL_RESULTS';


export const UPDATE_LANDING_YEAR = 'UPDATE_LANDING_YEAR';
export const UPDATE_LAUNCH_SUCCESS = 'UPDATE_LAUNCH_SUCCESS';
export const UPDATE_LANDING_SUCCESS = 'UPDATE_LANDING_SUCCESS';

export const ADD_RECORDS = 'ADD_RECORDS';

export const FETCH_RECORDS_START = 'FETCH_RECORDS_START';
export const FETCH_RECORDS_FAIL = 'FETCH_RECORDS_FAIL';